import React from 'react';
import { Header, Switch } from '@/components'
import { useLang } from '@/hooks'
import data from '@/assets/static/header.data';
import type { Metadata } from 'next'

export interface LayoutProps {
  children: React.ReactElement
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const RootLayout: React.FC<LayoutProps> = ({ children }) => {
  const { lang, handleLang } = useLang();
  return (
      <>
        <div className="bg-[url('assets/imgs/ParedDeConcreto.jpg')] bg-cover bg-no-repeat z-[-1] absolute top-0 left-0 w-full h-screen" />
        <div className='p-[10%]'>
          <Header
            caption={data.caption}
            navigation={data.navigation}
            Switch={<Switch onChange={handleLang} currentLang={lang} />}
          />
          {children}
        </div>
      </>
  )
}
